// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0xmZCArsxmaesRWGn9NAC1GaE5TZW6Yk',
    appId: '1:969191156033:web:76b8e8a94a2c142f9cd9c0',
    messagingSenderId: '969191156033',
    projectId: 'mytask-a48bb',
    authDomain: 'mytask-a48bb.firebaseapp.com',
    storageBucket: 'mytask-a48bb.appspot.com',
    measurementId: 'G-TKES462D53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4w2-eOub0IxCCoxwIFyvqZAjwOYGsTGE',
    appId: '1:969191156033:android:007272d0c61487199cd9c0',
    messagingSenderId: '969191156033',
    projectId: 'mytask-a48bb',
    storageBucket: 'mytask-a48bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBERPkC57uiHvzJeqXGUF0CyZZeeBX3zI4',
    appId: '1:969191156033:ios:ca43f1ca2f1c9b349cd9c0',
    messagingSenderId: '969191156033',
    projectId: 'mytask-a48bb',
    storageBucket: 'mytask-a48bb.appspot.com',
    iosBundleId: 'com.example.mytask',
  );
}
